transform:
  inputs:
    raw_data: data/data.txt
  outputs:
    trans_data: data/transformed_data.txt

  param:
    param0: 0.0
    param1: 0.0
    param2: 4

split:
  inputs:
    trans_data: data/transformed_data.txt
  outputs:
    test_data: data/test_data.txt
    train_data: data/train_data.txt
  param:
    test_fraction: 0.5

evaluate:
  inputs:
    test_data: data/test_data.txt
    train_data: data/train_data.txt
  outputs:
    result: reports/result.csv
    metric: reports/metrics.json


