transform:
  inputs:
    raw_data: data/data.txt
  outputs:
    trans_data: data/transformed_data.txt

  param0: 0.0
  param1: 0.1
  param2: 3

split:
  inputs:
    trans_data: data/transformed_data.txt
  outputs:
    test_data: data/test_data.txt
    train_data: data/train_data.txt

  test_fraction: 0.5

evaluate:
  inputs:
    test_data: data/test_data.txt
    train_data: data/train_data.txt
  outputs:
    result: data/result.csv
    metric: reports/metrics.json


