name: CML & DVC
on: [push]
jobs:

  #deploy-runner:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: iterative/setup-cml@v1
  #    - uses: actions/checkout@v3

  #    - name:
  #      env:
  #        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #        REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  #      run: |
  #          cml runner launch \
  #            --cloud "azure" \
  #            --cloud-region=switzerlandnorth \
  #            --cloud-type=s \
  #            --name=cml-vm \
  #            --labels="cml-vm"

  train-and-report:
    #needs: [deploy-runner]
    #runs-on: [self-hosted, cml-vm]

    runs-on: ubuntu-latest
    container: docker://cedricklinkert/dvc_super_simple:0.0.1

    steps:
      - uses: actions/checkout@v3
      - name: Pull data
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
        run: |
          mkdir data
          mkdir models
          mkdir reports
          dvc remote modify azure connection_string $AZURE_STORAGE_CONNECTION_STRING
          echo $AZURE_STORAGE_CONNECTION_STRING
          dvc pull --remote azure
          ls -a
      - name: Setup tmate
        uses: mxschmitt/action-tmate@v3

      #- name: Train model
      #    dvc repro
      #- name: Create CML report
      #  run: |
      #    # Compare metrics to main
      #    git fetch --depth=1 origin main:main
      #    dvc metrics diff --show-md main >> report.md
      #    # Plot training loss function diff
      #    dvc plots diff \
      #      --target loss.csv --show-vega main > vega.json
      #    vl2png vega.json > plot.png
      #    echo '![](./plot.png "Training Loss")' >> report.md
      #    cml comment create report.md
      #  env:
      #    REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
